DROP TABLE languages CASCADE;
DROP TABLE movies CASCADE;
DROP TABLE genres CASCADE;
DROP TABLE movies_genres CASCADE;
DROP TABLE producers CASCADE;
DROP TABLE movies_producers CASCADE;
DROP TABLE people CASCADE;
DROP TABLE movies_actors CASCADE;
DROP TABLE movies_directors CASCADE;
DROP TABLE rooms CASCADE;
DROP TABLE seats CASCADE;
DROP TABLE regionalizations CASCADE;
DROP TABLE abstract_screenings CASCADE;
DROP TABLE screenings CASCADE;
DROP TABLE movie_realizations CASCADE;
DROP TABLE movies_screenings CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE ticket_types CASCADE;
DROP TABLE reservations CASCADE;
DROP TABLE tickets CASCADE;
DROP TABLE journals CASCADE;
DROP TABLE reviews CASCADE;
DROP TABLE reviews_authors CASCADE;
DROP TABLE movies_reviews CASCADE;
DROP TABLE movies_screenwriters CASCADE;
DROP TABLE movies_composers CASCADE;

DROP VIEW movie_info CASCADE;
DROP VIEW regular_customers CASCADE;
DROP VIEW most_popular_seats CASCADE;
DROP VIEW regionalizations_langague_names CASCADE;
DROP VIEW full_screenings CASCADE;
DROP VIEW schedule CASCADE;
DROP VIEW full_schedule CASCADE;
DROP VIEW all_tickets CASCADE;

DROP FUNCTION short_format_review; 
DROP FUNCTION format_person;
DROP FUNCTION format_actor;
DROP FUNCTION format_movie_genres;
DROP FUNCTION format_movie_directors;
DROP FUNCTION format_movie_screenwriters;
DROP FUNCTION format_movie_actors;
DROP FUNCTION format_movie_composers;
DROP FUNCTION format_movie_producers;
DROP FUNCTION short_format_movie_reviews;
DROP FUNCTION abstract_screening_length;
DROP FUNCTION screenings_delete_check;
DROP FUNCTION screenings_insert_check;
DROP FUNCTION reservation_value;
DROP FUNCTION occupied_seats;
DROP FUNCTION regionalizations_langague_names_insert;
DROP FUNCTION schedule_insert;
DROP FUNCTION get_roomid;
DROP FUNCTION last_res_id;
DROP FUNCTION cant_buy_ticket;
DROP FUNCTION delete_reservation_if_empty;
DROP FUNCTION buy_ticket;
DROP FUNCTION user_history;
DROP FUNCTION get_start;
DROP FUNCTION cant_cancel_hour_before;
DROP FUNCTION cancel_ticket;